language: c
compiler:
  - gcc
  - clang
  
before_install:
  - sudo apt-get install cmake
  

script: 
  - ./cmake_oz.sh
  - cd ./build/Debug && make && make test
  - cd ./build/Release && make && make test
